from .contracts import MarketInstrument

INSTRUMENTS = (
    MarketInstrument(
        symbol="sh000001",
        provider_symbol="000001.SS",
        name="上证指数",
        market="CN",
        asset_type="index",
    ),
    MarketInstrument(
        symbol="sz399001",
        provider_symbol="399001.SZ",
        name="深证成指",
        market="CN",
        asset_type="index",
    ),
    MarketInstrument(
        symbol="sz399006",
        provider_symbol="399006.SZ",
        name="创业板指",
        market="CN",
        asset_type="index",
    ),
    MarketInstrument(
        symbol="sh000300",
        provider_symbol="000300.SS",
        name="沪深300",
        market="CN",
        asset_type="index",
    ),
    MarketInstrument(
        symbol="us_ixic",
        provider_symbol="^IXIC",
        name="纳斯达克指数",
        market="US",
        asset_type="index",
    ),
    MarketInstrument(
        symbol="us_spx",
        provider_symbol="^GSPC",
        name="标普500指数",
        market="US",
        asset_type="index",
    ),
    MarketInstrument(
        symbol="us_dji",
        provider_symbol="^DJI",
        name="道琼斯指数",
        market="US",
        asset_type="index",
    ),
    MarketInstrument(
        symbol="hk_hsi",
        provider_symbol="^HSI",
        name="恒生指数",
        market="HK",
        asset_type="index",
    ),
    MarketInstrument(
        symbol="hk_hstech",
        provider_symbol="HSTECH.HK",
        name="恒生科技指数",
        market="HK",
        asset_type="index",
    ),
    MarketInstrument(
        symbol="commodity_gold",
        provider_symbol="GC=F",
        name="黄金",
        market="COMMODITY",
        asset_type="commodity",
    ),
    MarketInstrument(
        symbol="commodity_oil",
        provider_symbol="CL=F",
        name="原油",
        market="COMMODITY",
        asset_type="commodity",
    ),
    MarketInstrument(
        symbol="fx_usd",
        provider_symbol="DX-Y.NYB",
        name="美元指数",
        market="FX",
        asset_type="currency_index",
    ),
)

INSTRUMENT_BY_SYMBOL = {instrument.symbol: instrument for instrument in INSTRUMENTS}
